apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-schedule-example.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "go-schedule-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 31224
      protocol: TCP
      name: http
  selector:
    {{- include "go-schedule-example.selectorLabels" . | nindent 4 }}
